import { Http } from '@angular/http';
import 'Swiper';
import 'ScrollMagic';
import 'Drift';
export declare class OsbMangaReader {
    http: Http;
    section: string;
    baseUrl: string;
    defaultSite: string;
    apiKey: string;
    isLoading: boolean;
    listStyle: boolean;
    hideMenu: boolean;
    mangaDetails: any[];
    mangaInfo: {};
    mangaChapter: {};
    siteFavouritesUrl: string;
    siteFavouritesData: any[];
    siteFavouritesDisplay: any[];
    mainListViewData: any[];
    mainListViewDisplay: any[];
    mainListViewDisplayCount: number;
    mainListViewDisplayPage: number;
    mainListViewDisplayPageLength: number;
    sliderSettings: {};
    viewerSettings: {
        whichManga: {};
        mangaTitle: string;
        chapter: number;
        chaptersTotal: number;
        chapterPagesTotal: number;
        isPage: number;
        isBookmark: boolean;
        hasBookmarks: boolean;
        hasNextBookmark: boolean;
        hasPrevBookmark: boolean;
        nextBookmark: {};
        prevBookmark: {};
        usingMagnifier: boolean;
    };
    userSettings: {
        nightMode: boolean;
        bookmarks: any[];
        favourites: any[];
    };
    constructor(http: Http);
    destroyEvents(): void;
    sliderOnInit(swiper: any): void;
    slideChangeStarting(swiper: any): void;
    slideChanged(swiper: any): void;
    chapterFinish(swiper: any): void;
    checkCache(): void;
    initSlider(): void;
    setNightMode(isNight: any): void;
    toggleNightMode(): void;
    showMagnifier(): void;
    hasMoreBookmarks(pageObj: any): boolean;
    hasLessBookmarks(pageObj: any): boolean;
    goToBookmark(bookmark: any): void;
    hasBookmarks(manga: any): boolean;
    checkBookmark(bookmark: any): boolean;
    setBookmark(manga: any, chapter: any, page: any): void;
    checkFavourite(manga: any): boolean;
    setFavourite(manga: any): void;
    getMangaChapter(manga: any, chapter: any): void;
    setMangaChapter(chapter: any): void;
    getMainMangaList(): boolean;
    viewMangaDetails(manga: any): void;
    setMainMangaList(data: any): void;
    getMoreMainManga(): void;
    startPagination(): void;
    getMangaDetails(manga: any, section: any, cache: any): boolean;
    setMangaDetails(manga: any, section: any, cache: any): void;
    getSiteFavourites(): boolean;
    setSiteFavourites(data: any): void;
}
